/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        "on-background": "#e5e2e1",
        surface: "#131313",
        "on-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#c1c8c9",
        primary: "#a8cdd4",
        "on-primary": "#0f353b",
        "primary-container": "#36595f",
        "on-primary-container": "#aaced5",
        secondary: "#edc062",
        "on-secondary": "#402d00",
        "secondary-container": "#805e00",
        "on-secondary-container": "#ffdc98",
        tertiary: "#b9cacc",
        "tertiary-container": "#465658",
        "on-tertiary-container": "#bacbcd",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        outline: "#8b9293",
        "outline-variant": "#414849",
        "secondary-fixed-dim": "#edc062",
        "on-primary-fixed-variant": "#294c52",
        "on-secondary-fixed": "#261900",
        "on-tertiary-fixed": "#0f1e20",
        "secondary-fixed": "#ffdea1",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed": "#001f24",
        "surface-bright": "#3a3939",
        "surface-dim": "#131313",
        "primary-fixed": "#c4e9f0",
        "primary-fixed-dim": "#a8cdd4",
        "on-tertiary": "#243335",
        "surface-tint": "#a8cdd4",
        "tertiary-fixed-dim": "#b9cacc",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#5c4300",
        "tertiary-fixed": "#d5e6e8",
        "inverse-primary": "#41646a"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "display": ["Outfit", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
